#!/usr/bin/env bash
# redirect to 404
# page not found

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
line="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}"
location="/etc/nginx/sites-enabled/default"
sudo sed -i "36i $line" "$location"
error="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
sudo sed -i "25i $error" "$location"
sudo service nginx restart
