#!/usr/bin/env bash
# install load balancer with round robin
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend anemdevop
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 30520-web-01 34.236.38.223
    server 30520-web-02  100.26.158.42 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

